version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DemianzxBackendDb=Host=postgres;Database=demianzxdb;Username=postgres;Password=postgres
      - DbProvider=postgres
      - Jwt__Key=EuHsgjFYTVz6xdF94epb252px7Cx2Tzx
      - Jwt__Issuer=demianzx-backend
      - Jwt__Audience=demianzx-frontend
      - BlobStorage__ContainerName=media
      - ConnectionStrings__AzureBlobStorage=YourAzureBlobStorageConnectionString
      # Configuración de CORS
      - Cors__AllowedOrigins__0=http://localhost:3000
      - Cors__AllowedOrigins__1=http://127.0.0.1:3000
      - Cors__AllowedOrigins__2=http://localhost:5173
      - Cors__AllowedOrigins__3=http://127.0.0.1:5173
      - Cors__AllowedOrigins__4=http://localhost:8000
      - Cors__AllowedOrigins__5=http://127.0.0.1:8000
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demianzxdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: