version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DemianzxBackendDb=Host=postgres;Database=demianzxdb;Username=postgres;Password=postgres
      - DbProvider=postgres
      - Jwt__Key=EuHsgjFYTVz6xdF94epb252px7Cx2Tzx
      - Jwt__Issuer=demianzx-backend
      - Jwt__Audience=demianzx-frontend
      - BlobStorage__ContainerName=media
      - ConnectionStrings__AzureBlobStorage=YourAzureBlobStorageConnectionString

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demianzxdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: